spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    username: gril
    password: gril
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8082
  servlet:
    context-path: /gril
cupSize: B
age: 18
content: "cupSize:${cupSize}, age:${age}"
girl:
  cupSize: A
  age: 20